THREADS=6
OUTDIR=~/fgonzaleznun/TFM/data/trimmedT_1/

for R1 in SRR*_1.fastq.gz
do
    SRR=$(basename $R1 | cut -d'_' -f1)
    R2=${SRR}_2.fastq.gz

    echo "Procesando SmartSeq2 - $SRR"

    cutadapt \
      -b AGATCGGAAGAGC -B AGATCGGAAGAGC \
      -g ATATCTCGAGGGCGCGCCGGATCCATAT \
      -g ATATGGATCCGGCGCGCCGTCGACATAT \
      -g ATATGGATCCGGCGCGCCCTCGAGATAT \
      -g ATATGGATCCGGCGCGCCGTCGAGATAT \
      -g ATATCTCGAGGGCGCGCCGGATCC \
      -g ATATGGATCCGGCGCGCCGTCGAC \
      -g ATATGGATCCGGCGCGCCCTCGAG \
      -G ATATCTCGAGGGCGCGCCGGATCCATAT \
      -G ATATGGATCCGGCGCGCCGTCGACATAT \
      -G ATATGGATCCGGCGCGCCCTCGAGATAT \
      -G ATATGGATCCGGCGCGCCGTCGAGATAT \
      -G ATATCTCGAGGGCGCGCCGGATCC \
      -G ATATGGATCCGGCGCGCCGTCGAC \
      -G ATATGGATCCGGCGCGCCCTCGAG \
      -g T{20} \
      -G T{20} \
      -a A{20} \
      -A A{20} \
      -b AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGAGCGCATCTCGTATGCCGTCTT \
      -B AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT \
      -b ACACGTCTGAACTCCAGTCACGAGCGCATCTCGTATGCCGTCTTCTGCTT \
      -q 20,20 \
      -e 0.2 \
      --overlap 5 \
      --minimum-length 25 \
      -j $THREADS \
      -o $OUTDIR/${SRR}_1.trim.fastq.gz \
      -p $OUTDIR/${SRR}_2.trim.fastq.gz \
      $R1 $R2
done
