---
title: "Descarga y preparación de metadatos"
author: "Francisco Manuel González Nuño"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 
# Datos
Los datos son provenientes del estudio con DOI 10.1126/science.aau6509 almacenados en GEO con el ID: GSE97693. Los códigos de análisis se pueden ver en [https://github.com/bianshuhui/CRC_code](https://github.com/bianshuhui/CRC_code).

```{r , message=FALSE, include=TRUE, echo=TRUE, warning=FALSE}
library(GEOquery)
library(dplyr)

conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("rename", "dplyr")
conflicted::conflict_prefer("filter", "dplyr")

data <- getGEO("GSE97693")$GSE97693_series_matrix.txt.gz
```

## Metadata

```{r , message=FALSE, include=TRUE, echo=TRUE, warning=FALSE}
meta <- pData(data)
meta <- meta %>%
  filter(grepl("scTrioSeq2Rna_CRC", meta$supplementary_file)) %>%
  mutate(clean_title = sub(" \\[.*\\]", "", title))

library(tidyr)
library(stringr)

metaData <- meta %>%
  select(
    sample = clean_title,
    relation
  ) %>%
  separate(
    sample,
    into = c("technology", "patient", "region", "cell_id"),
    sep = "_",
    remove = FALSE
  ) %>%
  mutate(
    region_long = case_when(
      str_detect(region, "^PT") ~ "Tumor Primario",
      str_detect(region, "^LN") ~ "Metastasis Nodo Linfático",
      str_detect(region, "^ML") ~ "Metastasis Higado",
      str_detect(region, "^MP") ~ "Metastasis post-tratamiento",
      region == "NC" ~ "Colon Normal"
    )
  )

write.table(metaData, "../Datos/MetaData.txt", sep = "\t", row.names = F, quote = F)

```


```{r}
metaData <- metaData %>% 
  mutate(
    BioSample = sub(".*/", "", relation)
  ) %>%
  select(-relation)

popData <- read.delim("../Datos/Metadata notes/population_data.txt") %>%
  rename(patient = Patient.ID)


SRAtable <- read.csv2("../Datos/Metadata notes/SraRunTable.csv", sep = ",") %>%
  select(Run, BioSample) %>%
  rename(SRA = Run)

metaSRA <- metaData %>%
  merge(SRAtable, by = "BioSample") %>%
  merge(popData, by = "patient")

write.table(metaSRA, "../Datos/metaSRA.txt")
saveRDS(metaSRA, "../Datos/MetaData.rds")
```

