---
title: "Pseudobulk y expresión diferencial"
author: "Francisco Manuel González Nuño"
output:
  html_document:
    toc: true              
    toc_depth: 2
    toc_float: true        
    number_sections: true  
    theme: cosmo           
    highlight: tango       
    code_folding: "show"   
    code_download: true    
    df_print: paged        
    self_contained: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r , message=FALSE, include=TRUE, echo=TRUE, warning=FALSE}
library(dplyr)
library(ggplot2)
library(ggrepel)
library(SingleCellExperiment)
library(scater)
library(scuttle)
library(edgeR)

conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("filter", "dplyr")
conflicted::conflict_prefer("rename", "dplyr")

source("Functions/contraste.R")
```

```{r , message=FALSE, include=TRUE, echo=TRUE, warning=FALSE}
sce_raw <- readRDS("../Datos/sce_raw.rds")
sce2 <- readRDS("../Datos/sce_2.rds")
# sce_raw <- sce_raw[, colnames(sce_raw) %in% colnames(sce2[,sce2$annMid %in% c("Epi", "EpiT")])]
sce_raw <- sce_raw[, colnames(sce_raw) %in% colnames(sce2[, sce2$cellAnnot == "Epithelial_cells"])]
rm(sce2)
```

# Pseudo-Bulk
Nos interesa hacer agreación por paciente y tejido.

```{r , message=FALSE, include=TRUE, echo=TRUE, warning=FALSE}
sce_raw$pb_ids <- paste(sce_raw$patient,
                    sce_raw$region_long,
                    sep = "_")


pb <- aggregateAcrossCells(
  sce_raw,
  ids = sce_raw$pb_ids,
  use.assay.type = "counts"
)
```

```{r , message=FALSE, include=TRUE, echo=TRUE, warning=FALSE}
#excluimos metastasis post-tratamiento porque solo tendría una pseudo-muestra
# pb <- pb[, !(pb$region_long %in% c("Metastasis post-tratamiento"))]
pb <- pb[, !(pb$patient %in% c("CRC01", "CRC02"))]

pb$patient <- factor(pb$patient)
pb$patient <- droplevels(pb$patient)

pb$region_long <- factor(pb$region_long)
pb$region_long <- droplevels(pb$region_long)
pb$region_long <- relevel(pb$region_long, ref = "Tumor Primario")
```

## PCA

```{r , message=FALSE, include=TRUE, echo=TRUE, warning=FALSE, fig.width=6}
pb <- logNormCounts(pb)
pb <- runPCA(pb)
plotPCA(pb,
        shape_by = "region_long",
        colour_by = "patient") +
  theme_minimal() +
  labs(title = "PCA de pseudo-bulk",
       x = "PC1",
       y = "PC2") +
  guides(shape = guide_legend(title = "Región"),
         colour = guide_legend(title = "Paciente"))
table(pb$patient, pb$region_long)
saveRDS(pb, "../Datos/pb.rds")
```

#Análisis de expresión diferencial



```{r , message=FALSE, include=TRUE, echo=TRUE, warning=FALSE}
targets <- base::setdiff(
  levels(pb$region_long),
  "Tumor Primario"
)

all_results <- list()

for (target in targets) {
  
  cat("\nAnalizando contraste: ", target, " vs Tumor Primario\n")
  
  tab <- contraste_pb(
    pb = pb,
    target = target,
    ref = "Tumor Primario",
    lfc = log2(1.5),
    robust = T
  )
  
  suffix <- make.names(target)
  
  tab <- tab %>%
    rename_with(
      .fn = ~ paste0(.x, "_", suffix),
      .cols = -gene_id
    )
  
  all_results[[target]] <- tab
}
#fusionamos resultados
de_merged <- purrr::reduce(all_results,
                           full_join,
                           by = "gene_id")

#se añade gene symbol
de_merged <- de_merged %>%
  mutate(
    gene_name = rowData(pb)$gene_name[match(de_merged$gene_id,
                                                   rownames(pb))]
    ) %>%
  select(gene_id, gene_name, everything(),
         -starts_with("unshrunk"))

write.csv(de_merged, "../Results/DE_pseudobulk.csv", row.names = FALSE)
```

# Volcano plots

```{r , message=FALSE, include=TRUE, echo=TRUE, warning=FALSE, fig.width=10}
for(target in targets){
  suffix <- make.names(target)
  
  tab <- de_merged %>%
    select(gene_id, gene_name, 
           paste0("logFC_", suffix),
           paste0("FDR_", suffix),
           paste0("PValue_", suffix)) %>%
    rename(logFC = paste0("logFC_", suffix),
           FDR = paste0("FDR_", suffix),
           PValue = paste0("PValue_", suffix))

  tab <- tab %>%
    mutate(
      log10FDR = -log10(FDR),
      sig = case_when(
        logFC > 1 & log10FDR > -log10(0.05) ~ "UP",
        logFC < -1 & log10FDR > -log10(0.05) ~ "DOWN",
        TRUE ~ "NS"
      ),
      tag = case_when(
        sig != "NS" ~ gene_name,
        TRUE ~ NA_character_
      ))
      
  p <- ggplot(tab, 
              aes(x = logFC, 
                  y = log10FDR)) +
    geom_point(aes(color = sig), 
               alpha = 0.6) +
    scale_color_manual(values = c("UP" = "#E69F00", 
                                  "DOWN" = "#56B4E9", 
                                  "NS" = "grey60")) +
    geom_vline(xintercept = c(-1, 1), 
               linetype = "dashed", 
               color = "black") +
    geom_hline(yintercept = -log10(0.05), 
               linetype = "dashed", 
               color = "black") +
    geom_text_repel(aes(label = tag),
                    size = 3,
                    max.overlaps = 10,
                    show.legend = FALSE) +
    theme_minimal() +
    labs(title = paste("Volcano plot:", 
                       target, "vs Tumor Primario"),
         x = "Log2 Fold Change",
         y = "-Log10 pValue") +
    theme(legend.title = element_blank())
  
  print(p)
    
  }

```

```{r, message=FALSE, include=TRUE, echo=TRUE, warning=FALSE}
de_merged %>%
  filter(!is.na(logFC_Metastasis.Nodo.Linfático)) %>%
  filter(PValue_Metastasis.Nodo.Linfático < 0.05) %>%
  arrange(desc(logFC_Metastasis.Nodo.Linfático)) %>%
  pull(gene_name) %>%
  write.csv("../Results/candidates_NL_PT.csv", row.names = F, col.names = F)

de_merged %>%
  filter(!is.na(logFC_Colon.Normal)) %>%
  filter(PValue_Colon.Normal < 0.05) %>%
  arrange(desc(logFC_Colon.Normal)) %>%
  pull(gene_name) %>%
  write.csv("../Results/candidates_TP_NC.csv", row.names = F, col.names = F)
```


```{r}
sessionInfo()
```